services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
    # network_mode: host
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
